
const descriptions = [
  `Anlamak ve anlaşılmak iletişim yetkinliğinin temel bileşenleri, iletişim yetkinliği de başarı açısından kilit yetkinliklerden birisidir. 
  İnsan sosyal bir varlıktır. Sürekli olarak sosyal ortamların içindedir. Tek başına yaşaması, başarılı olması ve kendini gerçekleştirmesi mümkün değildir. Sosyal ve iş yaşamında üstlenilen roller, başkaları ile birlikte olmayı, sonuca birlikte ulaşmayı gerektirir. Tüm bunların gerçekleşmesi, anlamak ve anlaşılmak dinamiklerinin iyi çalışmasına bağlıdır.
  Sizden ne beklendiğini iyi anlamak ve bu konuda neler yatığınızı iyi anlatabilmek, dışarıdan nasıl göründüğünüzü, nasıl algılandığınızı bilmek ve varsa yanlış anlamaları, algı hatalarını düzeltebilmek, meseleleri açık ve net olarak ortaya koyabilmek, böylece belirsizlikten doğabilecek karmaşa ve zaman kayıplarının önüne geçebilmek, zorlayıcı bile olsa, gerektiğinde çekinmeden duygu ve düşüncelerinizi ifade etmek ve geribildirimleri bir hediye olarak görebilmek, başkalarına yapıcı ve geliştirici geribildirimler verebilmek, olası görüş ayrılıkları ya da  çatışmaları tüm tarafların yararına olacak şekilde çözmek için çaba sarf etmek gerekir. 
  Tüm bu davranışlar iş yaşamındaki gizli başarı faktörleridir. Belirsizlik, hedefe odaklanma ve yön birliğini zorlaştırır. Netliğin olmadığı durumlarda hatalar, kayıplar, kaçaklar ve maliyetler artar. İletişim boşluklarını varsayımlarla doldurmalar ya da yanlış anlamalardan kaynaklanan çatışmalar gereksiz yere enerji tüketebilir. Bu yüzden iyi iletişim yetkinliği iş birliğinin anahtarıdır. Birlikte başarmak için stratejik bir çarpandır. 
  Başkalarını dinlemek, onlarla empati kurabilmek, onları anlamak, buna göre kendini net bir şekilde ifade etmek, varsa anlaşmazlıkları çözmek, güçlü iş birlikleri kurmak, yazılı ve sözlü iletişimi ve beden dilini en iyi şekilde kullanmak, mesleki yetkinliklerinden bağımsız, iş dünyasının bir adayda aradığı öncelikli yetkinlikler arasındadır.`,
  ["Anlama ve anlaşılma sürecinde özellikle sorun yaşadığınız ya da gelişim ihtiyacı olan alanları bulmaya çalışın ve bunların üzerine bilinçli bir şekilde odaklanın. Kendi iletişim analizini yapın.",
    "İletişim zihinde başlar. Önyargısız ve her türlü görüşe açık olmak sağlıklı iletişimin temelidir. İletişim sırasında size güven duyulmasını sağlayacak olan yapıcı, sabırlı, samimi, tutarlı ve dürüst bir duruş sergilemenizdir. Bu konularda kendinizi izleyip geliştirin.",
    "İletişimde sizi başarıya götürecek olan tüm bilgi ve teknikleri öğrenin. Bunun için Tobeto’nun iletişim alanında size sunduğu harika eğitimleri bitirin.",
    "Özellikle geliştirmek istediğiniz alanla ilgili bilinçli denemeler yapın.",
    "İfadelerinizin basitleşmeye ihtiyacı varsa, karmaşık bir konuyu on cümlede özetlemeyi deneyin ya da bir akıl haritası ile tek sayfada özetleyin.",
    "Sunum konusunda ilerlemek için hazırlık yapıp arkadaşlarınıza ve sonra başka kişilere sunumlar yapmayı deneyin.",
    "Yazılı iletişimi düzeltmek için deneme yazıları yazın ve geribildirim alın.",
    "Yeni öğrendiğiniz dinleme tekniklerini uygulayın, anlayışınızı ve iletişimi derinleştirmek adına güçlü sorulara başvurun ve sonuçları gözlemleyin.",
    "“İletişim zekâsı”, “sosyal zekâ”, “etkili iletişim” gibi anahtar kelimelerle aramalar yapın ve kendi iletişim stratejinizi oluşturun.",
    "Öncelikle ana dilinizi doğru kullanın. Dil kurallarına, telaffuza, kelime seçimlerine özen gösterin. Dil, düşünmenin ana mecrasıdır. Dil altyapısı ile kelime ve kavram bilgisi, iyi düşüncenin ve doğru iletişimin temelidir.",
    "İletişimini güçlü gördüğünüz kişileri gözlemleyip analiz edin. Neyi iyi yaptıklarını bulmaya çalışın. Fırsat bulduğunuz her durumda bu kişilerin stratejilerini ve deneyimlerini kendilerinden dinlemeye çalışın."
  ],
  " ",
  `Tobeto ‘İşte Başarı Modeli’nin son yetkinliği yeni dünya ile ilgilidir. Bu yetkinlik, diğer yedi yetkinlikten farklı olarak, yeni dünya ile ilgili farkındalık yaratmak ve herkesin kendisini olabildiğince buna hazırlaması konusunda yönlendirici olması için modele eklenmiştir. Zira içinde bulunduğumuz zamanlar önemli bir geçiş sürecine işaret etmektedir. Dijital teknolojilerle birlikte yaşanan dönüşümler hayatın her alanını yeninden şekillendirmektedir.
  İş dünyası ve şirketler de bu dönüşümün hem lokomotifi hem de etkilenenidir. Teknolojinin bu kadar yaygınlaşması ve karmaşık hale gelmesi, onu kullanabilecek nitelikte donanımlı insanlar gerektirmektedir. Birçok araştırma göstermektedir ki, hızlı teknolojik gelişmeler karşısında gereken yetenek altyapısı oluşturulamamıştır. Bu yüzden birçok şirket, özellikle teknoloji yoğun pozisyonlarda yetenek açığı çekmektedir. Bu açığı kapatmak için kendi içinde gelişim programları düzenleyen pek çok şirket var.
  İşin daha dramatik boyutu, bazı meslekler artık kendini tamamen teknolojiye bırakmış durumda ve artık bu meslek alanlarında çalışanların kendilerini başka alanlarda çalışacak şekilde geliştirmesi bir zorunluluk. Tüm bu dönüşüm süreci içinde; yeni dünyayı anlamış, bu dünyada başarılı olabilecek dijital ve teknoloji yetkinliklerine sahip adayların istihdamı kuşkusuz daha kolay. Bu konudaki gelişim ihtiyacı sadece istihdamla ilgili de değil çünkü bu beceriler gündelik yaşamda da çok önemli hale gelmiş durumda. İnterneti iyi kullanan, aradığı tüm bilgilere ulaşabilen, ihtiyacına göre dijital uygulamaları arayıp bulan, siber dünyada güvenliğini koruyabilen tüm bireyler birçok alanda öne çıkıyor. Ayrıca bu dünya fırsatlar dünyasıdır. Yeni mecralar, yeni işler, yeni para kazanma biçimleri ortaya çıkarken bu fırsatları ancak yeterli donanıma sahip bireyler yakalayabilecek. Tüm bu açılardan bakıldığında bu yetkinlik, diğer tüm yetkinliklerin gücünü artırması açısından önemli.`,
  ["Tobeto size yeni teknolojileri ve yeni dünyanın kodlarını tanıtan eğitimler sunmaktadır. Bu eğitimleri tamamlayın.",
    "Bununla birlikte bu alan son derece dinamik ve sürekli olarak yeniliklerin ortaya çıktığı bir alandır. Bir alışkanlık olarak tüm bu yenilikleri takip edin.",
    "“Dijital okuryazarlık”, “teknoloji okuryazarlığı”, “yeni medya okuryazarlığı”, “bilgi okuryazarlığı” gibi anahtar kelimelerle yeni okuryazarlıkları araştırın.",
    "Özellikle çalışmak istediğiniz alandaki en yeni teknolojilerle ilgili araştırmalar yaparak buradaki bilgi ve beceri altyapınızı taze tutun.",
    "Yeni dünya, 21. yy. becerileri ile ilgili birçok araştırma ve rapor yayınlanmaktadır. Bunları bulup inceleyin. Özellikle hangi beceriler ön plana çıkıyor ya da çıkacak, o konularda gelişime öncelik verin.",
    "Tüm bu eğitim ve araştırmalarınız sonrasında, kritik gördüğünüz kriterler üzerinden kendiniz için bir analiz yapın ve kendinize bir puan verin.",
    "Dijital teknolojilerde sadece tüketici olmak değil aynı zamanda üretici olmak için de çaba gösterin. En basitinden dijital içerik üretme tarafında temel sosyal medya paylaşımlarının ötesinde daha profesyonel denemeler yapabilirsiniz.",
    "Yazılım alanında çalışmasanız bile fırsatınız varsa temel düzeyde yazılım öğrenmeye çalışın. En azından yazılımcılarla birlikte çalışabilecek kadar, yazılım dünyasının temel kavramlarına aşina olun.",
    "Yine benzer şekilde, veri bilimi alanında çalışmasanız bile bu alanda kendinizi olabildiğince geliştirin.",
    "Dijital dünyada iş fırsatlarını araştırın. Kendi adınıza ya da çalıştığınız kurum için girişim denemelerinde bulunabilirsiniz.",
    "‘Netiket’ kavramını araştırın ve dijital mecralardaki varlığınızı olabildiğince bu sınırlar içinde tutmaya özen gösterin.",
    "Özellikle bireysel düzeyde siber güvenlik risklerini ve önlemlerini araştırın. Buradaki önemleri olabildiğince uygulamaya çalışın. Özellikle bu konularda deneyimsiz olan yakınlarınıza yardımcı olun.",
    "Dijital dünyaya hâkim, yeni teknolojileri yakından takip eden kişilerle birlikte öğrenme ve paylaşım grupları kurun. Herkesin bilgisi ve deneyimini ortak bir akla dönüştürün. Burada üretilen bilgilerle başkalarına olabildiğince destek olun."
  ],
  "",
  `Sonuç odaklılık çekici bir güçtür. İstenilen başarı noktasına konulmuş bir çıpadır. Kişilerin, işlerin, projelerin, kurumların hedefine ulaşmasını sağlayan disiplindir. Fikirlerin hayata geçmesi ve sonuca ulaşması sürecidir. Bu yetkinlik yürütücü bir yetkinliktir. Bu açıdan diğer tüm yetkinliklerin ürettiği değerin tamamlayıcısı, bitiricisidir. Bu yüzden çok önemlidir. Kendinizi çok iyi tanıyor, hedeflerinizi çok doğru belirlemiş, harika iş birlikleri kurmuş ve çok yaratıcı çözüm fikirleri üretmiş olabilirsiniz. Ama tüm bunlar, hayata geçip sonuçlanmadıkça hiçbir anlam ifade etmez. Kurumların dünyası, hatta insanların kendi dünyaları bile, hayata geçmeyen nice fikirle doludur.
Burası stratejik bir alan olmaktan çok bir uygulama alanıdır. Belirlenmiş olan hedef ne olursa olsun ona ulaşabilme yetkinliğidir. Bunun için öncelikle iyi bir planlama gerekir. Plan, hedefe ulaşmak için bana yol gösteren bir haritadır. Plan, sürecin neresinde olduğumu takip edebildiğim bir ölçektir. Plan, belirsiz ve karmaşık işleri netleştiren ve herkesin üzerinde uzlaşabildiği bir kolaylaştırıcıdır. Plan doğrultusunda gerekli organizasyonu yapmak, öncelikleri ve zamanı yönetmek, zorlukların üstesinden gelmek, azim ve kararlıkla planı uygulamak da bu yetkinliği oluşturan bileşenler arasındadır. 
Bitirici ve tamamlayıcı bir yetkinlik olması açısından kurumlar tarafında çok aranan bir yetkinliktir. Zira sonuca giden yol zorluklarla, tuzaklarla ve gizli ya da açık yavaşlatıcılarla doludur. Mükemmele ulaşma isteği örneğin, özünde iyi bir şey olmasına karşın mükemmeliyetçilik, sonucu ulaşma noktasında en büyük engellerden birisi olabilir. Bu yolda inisiyatif ya da risk alınması gereken anlar olabilir. Asıl mesele, tüm bunlara durumsal olarak karar verebilmektir. O yüzden başarı ve sonuç odaklılık olmak tüm yetkinliklerin dışında tek başına odaklanılması gereken bir yetkinliktir. `,
  ["Kendi sonuç odaklılık seviyenizle ilgili bir analiz çalışması yapın. Başkalarına “bir işi ver ve unut” seviyesinde güven verebiliyor musunuz, bunu değerlendirin.",
    "Sonuç odaklılıkla ilgili tüm kritik bileşenleri öğrenin. Bunun için sunulan tüm Tobeto eğitimlerini tamamlayın.",
    "Bu eğitimlere ek olarak, “planlama”, “sonuç odaklılık”, “zaman yönetimi”, “azim”, “dayanıklılık”, “performans engelleyicileri” gibi anahtar kelimelerle araştırmalarınızı derinleştirebilir ve güçlü bir bilgi altyapısı oluşturabilirsiniz.",
    "Planlama ile ilgili bir deneyiminiz olsa da olmasa da yeni baştan üzerinde çalışın. Yeni nesil çevik planlama ve iş yapma yöntemlerini araştırın ve kendi yaklaşımınızı geliştirin.",
    "Farklı metodolojiler kullanarak planlama denemeleri yapın. Planları güncel tutma, revize etme ve sonuna kadar gitme konusunda kendinizi zorlayın.",
    "Dijital planlayıcı, takvim, iş yönetimi, hatırlatıcı gibi verimlilik araçlarını inceleyin ve kendinize uygun olanları kullanın. Bu gibi dijital araçları kullanma becerinizi geliştirin. Ekibinizle ya da arkadaşlarınızla birlikte ortak dijital platformlarda çalışma kabiliyetinizi güçlendirin.",
    "Öncelikleri belirleme ve zaman yönetimi konusunda kendinizi gözlemleyin. Ne kadar başarılısınız? Son dakikaya kalan işleriniz ne kadar çok? Peki ya vakit yetmediği için yetiştiremedikleriniz… Bunların nedenlerini ve çözüm yollarını araştırın ve kendi zaman yönetimi disiplininizi oluşturun.",
    "İş yapma süreçlerinde sizi en çok zorlayan durumları ve bunların ne zaman ortaya çıktığını analiz etmeye çalışın. Örneğin hangi durumlarda çekilme ya da bırakma ihtiyacı hissediyorsunuz. Erteleme davranışına ne kadar sıklıkla başvuruyorsunuz?",
    "Ne kadar azimlisiniz? Ya da zorluklar karşısında ne kadar dayanıklısınız? Azim ve dayanıklılık dinamiğini çok iyi araştırın. Buradan elde edeceğiniz bilgilerle birlikte işinizde, hayatınızla denemeler yaparak bu alanlarda güçlenebilirsiniz.",
    "Eylem ve sonuç odaklılık noktasında başarılarınızı ve deneyimlerinizi paylaşın ve başkalarına ilham olmaya çalışın.",
    "Başarılı iş bitiricileri bulup onları gözlemleyin. Yapabiliyorsanız deneyimlerini ve yöntemlerini öğrenin. Başarıya ulaşmış insanlarla ilgili yazılmış kitapları okuyun kendinize dersler çıkarın."
  ],
  " ",
  `Profesyonellik bir alanda uzmanlaşma, meslek sahibi olma ve bu alanda bir kurumda ya da kendi işinde çalışma ile ilgili bir kavramdır. Kurumlar da profesyonel yapılanma içinde olan örgütlerdir. Kendilerine göre kuralları, ritüelleri, iş yapma şekilde, beklentileri olabilir. Bunların bazıları yazılıdır, bazıları da hiçbir yerde yazılmadığı halde kurumun havasında, kültüründe varlığını sürdürebilir. Bunlar bir kurumun yapısı ve karakteri ile ilgilidir. O kurumdaki çalışanlar da bunları bilir, bunları kabul eder ve bunlara uygun davranışlar sergiler. Kuruma özgü olanlar dışında tüm kurumsal iş hayatında ortak olan bazı profesyonellik beklentileri de vardır. Bu bir duruştur ve istihdamı kolaylaştırır.
  Profesyonel davranışın temeli, hangi işi yapıyorsan yap onu en iyi şekilde yapmaya çalışmaktır. Okulların, Tobeto gibi gelişim platformlarının verdikleri geliştirme hizmetleri bu açıdan profesyonel yaşama hazırlık niteliğindedir. İşinde en iyi olmaya çalışmak kişinin her şeyden önce kendisine duyacağı saygı ile ilgilidir. Diğer taraftan işe girilen kurumun kurallarını ve çalışanlardan beklentilerini en iyi şekilde öğrenmek ve bunlara uymak da profesyonellik gereğidir. Bu da çalıştığım kuruma göstereceğim saygı ile ilgilidir. Buna göre, işimde yetkinimdir, sorumluluk alırım, elimden geleni sonuna kadar yaparım ve yaptıklarımla ilgili de hesap verebilirim. Tutarlıyımdır, başkalarına adil ve ön yargısız yaklaşırım. Konuşmalarımla eylemlerim de birbiri ile uyumludur. Başkalarının haklarına saygı duyarım. Gizlilik ve güvenlik gerektiren konularda yüksek hassasiyet gösteririm. İşin ve başkalarının güvenliğini riske atmam. Kıyafetlerim ve verdiğim görüntü kurumumun kabul ettiği sınırlar içindedir. Kurum dışında bir temsilci olduğum bilinci ile hareket ederim. Doğaya saygılı olarak işimde kullandığım kaynakları israf etmem.
  Kuşkusuz profesyonel duruş altında başka birçok nitelikten bahsetmek mümkündür. Aslında bundan önceki tüm yetkinlikler de profesyonel duruşu destekleyen yetkinliklerdir. Profesyonellik, tüm bu yetkinlikler ve dikkat edilmesi gereken bazı kurallarla birlikte ortaya koyduğumuz resmin dışarıdan algılanmasıdır. Bir bireyin kendi markasını ve itibarını destekler. Kurumsal kurumlar arasında geçişişi kolaylaştırır. Burada özellikle ilk defa işe girecek genç arkadaşların iş başı öncesinde bu alanda olabildiğince kendini geliştirmesi, en başından iyi bir izlenim oluşturması açısından yararlı olur.`,
  ["Profesyonellik nedir, profesyonel davranış ve duruş nasıl bir şeydir, bunları iyi bir şekilde araştırın. Bu araştırmalar sonrasında kendinize bir profesyonellik puanı verin. Sonra bu puanı yükseltmeye çalışın.",
    "Tobeto tarafından bu alanda sunulan eğitimler bu alanda size tüm temel bilgileri sağlayacaktır.",
    "Diğer tüm İşte Başarı yetkinlikleri de profesyonel duruşunuza katkı sağlayacak niteliktedir. Dolayısıyla diğer yetkinlikler için paylaşılan tüm gelişim önerileri aynı zamanda profesyonellikle ilgili önerilerdir. Ayrıca diğer tüm Tobeto eğitimleri de profesyonel dünya için hazırlanmış eğitimlerdir. Eğitimlerin tamamını bitirdiğinizde profesyonellikle ilgili çok geniş bir bakış açısına sahip olacaksınız.",
    "Özellikle ilk defa kurumsal dünyada işe başlayacak olan genç arkadaşların staj, şirket gezisi, şirket projeleri vb. yollarla şirketlerle erken dönemde ilişki içinde olması önemli düzeyde bir görgü kazandıracaktır.",
    "Herkesin kurumsal dünyada çalışan bir yakını ya da yakınlarının yakınları olabilir. Onlarla özellikle kurumlardaki yaşam, kurallar, beklentiler, hoş karşılanmayan davranışlar vb. ile ilgili sohbet edebilirsiniz.",
    "Şirketlerin iş ilanları, faaliyet ve kurumsal sosyal sorumluluk raporları, sosyal medya paylaşımları gibi kamuya açılan bilgileri de kurumsal yaşamla ilgili ipucu verecek bilgiler barındırır. Bunları da olabildiğince incelemenizi öneririz.",
    "Sürdürülebilirlik bakışı ile çevreye ve doğaya saygılı olma da özellikle kendinizi geliştirmeniz gereken bir insanlık ve profesyonellik alanıdır. Geçek bir profesyonel, başarının peşinden koşarken insanları, çevreyi, doğayı ve kaynakları en iyi şekilde koruyandır.",
    "Profesyonellik, adalet, dürüstlük, sorumluluk sahibi olma, sözünde durma, ölçülülük, vb. gibi insani erdemlerin üzerinde yükselen bir olgudur. İyi ve erdemli insan olma çabaları aynı zamanda iyi bir profesyonel olmanıza da destek olacaktır."
  ],
  " ",
  `Yaratıcı düşünme ve sıra dışı çözümler geliştirebilme yetkinliği işlerin ilerlemesi ve sürdürülebilirlik açısından en önemli yetkinliklerden birisidir. Burası analiz ve keşif ile başlayan çözüm geliştirme alanıdır. Geliştirilen çözüm bazen bir sorunla ilgili olabilir, sorun ortadan kalkar. Bazen bir yenilikle ilgili olabilir, ortaya yepyeni bir şey çıkar. Çözüm bazen çok basit nitelikte olabilir, bazen de çözümle o kadar önemli bir problem ortadan kalkar ya da öyle bir buluş yapılır ki etkisi çok büyük olabilir. Bu açıdan tüm yetkinlikler içindeki en fantastik yetkinlik belki de budur. Potansiyeli yüksektir.
Yaşam denen süreç son derece dinamik bir süreçtir. Bir konuda üretilen çözüm kısa zaman sonra boşa çıkabilir. Ya da yepyeni durumlar karşısında yepyeni çözümler geliştirmek gerekebilir. Kimsenin görmediği bir problemi görebilmek ya da tanımlayabilmek bile tek başına bir dönüşüm süreci başlatabilir. Bu açıdan çözüm odaklılık, özellikle karmaşık ve değişken karakterli bir dünyada, en gerekli yetkinliklerden birisidir. Çözülecek şeyi ya da problemi çok iyi bir şekilde analiz edebilmek yetkinliğin kritik bileşenlerinden birisidir. Burada analitik düşünme becerisi ön plana çıkar. Diğer bileşen, problem çözme sürecidir. Bu, problemi tanımlama, olası çözümleri belirleme, uygun çözümü seçme, bunu uygulama ve sonuçları değerlendirme şekliden kabaca tarif edilebilecek bir süreçtir. Bu süreçten harikalar yaratacak olan ise yaratıcı düşünce bileşenidir. Bir bütün olarak yaratıcı ve çözüm odaklı bakış da tıpkı gelişim odaklı bakış gibi bir zihin yapısı, dünyaya bakış şeklidir. 
İş ortamları da son derece dinamik ve değişkendir. Zorluklar ve sorunlar ile iyileştirme ve yenilik fırsatlarının sürekli olarak ortaya çıkması, işin doğal bir karakteridir. Bu yüzden çalışanların çözüm bulma, geliştirme ve bunları uygulayabilme yetkinliği de aynı şekilde gerekli ve önemlidir. Küresel ölçekte ses getiren buluşların ya da yenilikçi uygulamaların çıkış noktalarına bakıldığında, orada sorunları görebilen, analitik düşünebilen, çözüm odaklı yaklaşım sergilen ve yaratıcı bir kafa yapısına sahip birilerinin olduğu görülecektir.`,
  ["Ne kadar analitik düşünebiliyorsunuz ne kadar çözüm odaklısınız ne kadar yaratıcısınız sorularının peşinde kendinizi analiz edin ve özellikle odaklanmanız gereken alanları belirlemeye çalışın.",
    "Tobeto’nun bu konuda size yardımcı olacak eğitimlerini mutlaka tamamlayın.",
    "“Analitik düşünce” üzerine özellikle araştırma yapın. Öğrendiklerinizden yola çıkarak kendi düşünme süreçlerinizi gözlemleyin ve analitik düşünmeyi geliştirecek denemeler yapın.",
    "Bir problem çözme metodolojiniz olsun. Var olan yaklaşımları inceleyin ve kendi sentezinizi yapın. Bir problemle karşılaştığınızda kendi yaklaşımınızı uygulayın. Deneyimle birlikte yaklaşımınızı geliştirin.",
    "Sorunları, durumları ya da çözümleri görselleştirme üzerine özellikle odaklanın. Görselleştirme sadece bir gösterim değil çözümü kolaylaştıran güçlü bir araçtır.",
    "“Yaratıcı düşünme” alanında da derinlemesine araştırma yapın. Yaratıcılık denen olgunun dinamiklerini iyi anlamaya çalışın. Teknikleri öğrenin.",
    "Buradaki tüm anahtar kelimelerde aramalar yaparak bilgi altyapınızı güçlendirin. Bu alan özellikle birlikte öğrenmenin çok iyi çalıştığı bir alandır. Bir öğrenme grubu kurun ve herkes araştırma yapsın, bilgi ve deneyimlerinizi paylaşın, ortak çözümler ya da çözüm metodolojileri geliştirin.",
    "Beyin fırtınası gibi yöntemleri sıklıkla uygulayın. Bu gibi yöntemler grupların ortak aklını ortaya çıkarması açısından çok kıymetlidir.",
    "Yaratıcılık ve yenilikçilik hikayelerini okuyun. Çıkış noktasını ve süreci analiz edin. Alınması gereken dersleri ya da kritik aksiyonları kayıt altına alıp kendi metodolojinize katın.",
    "Kendi aklınıza başkalarının aklını eklemleyerek daha büyük bir zihinsel kaynak ile yaratıcı çözümler geliştirmeye çalışın. Bunu nasıl yapabileceğiniz üzerine odaklananın. Burada çevrim içi iş birliği ve birlikte çalışma araçlarını en iyi şekilde kullanabilirsiniz.",
    "Bulduğunuz çözümlerin yarattığı etkiyi görünür hale getirin ve paylaşın. Başkalarına ilham olun.",
    "Büyük ya da küçük, iyi çözümler geliştiren herkesi olabildiğince takdir edin, değer verdiğinizi gösterin.",
    "Çözüm odaklı ve yenilikçi kişileri yakın takibe alın. Ulaşabildikleriniz olursa mutlaka deneyimlerini almaya çalışın."
  ],
  " ",
  `Kendini tanıma ve yönetebilme, sadece iş hayatında değil, yaşam boyu başarı için ilk odaklanılması gereken yetkinliktir. Bu açıdan “kendini tanımak” merkezi yetkinliktir. Herkes kendini doğal olarak tanıdığını düşünebilir ama insanın kendi coğrafyası içinde hiç gidilmemiş, bilinmeyen, tam anlamıyla keşfedilmemiş, keşfedilmiş ama haritası çıkarılmamış, adı konulmamış, yeteri kadar tanımlanmış yerler olabilir. Üstelik bu alanların kendisi de dinamiktir. Yaşla, deneyimle, yeni öğrenimler ve farkındalıklarla birlikte kendine yolculuğun tabiatı da değişir.
  Bu yolculukta şu keşif soruları yardımcı olabilir: Ben kimim? Yaşam amacım ne? Benim değerlerim, olmazsa olmazlarım neler? Doğuştan gelen ve bana güç veren özelliklerim hangileri? Beni zorlayan, yeteri kadar iyi olmadığımı düşündüğüm niteliklerim neler? Bana verilen altyapı üzerine şu ana kadar hangi bilgi ve becerileri inşa ettim? Hangi tutumları geliştirdim? Hangi alanda ne kadar yetkinim ve kapasitemi ne oranda kullanabiliyorum? Duygusal dinamiklerimin ne kadar farkındayım? Hangi durumda ne tür tepkiler veriyorum? Belirli zamanlarda nasıl davranışlar sergiliyorum? Hangi alanlarda iç çatışmalarım var? Beni mutlu eden şeyler neler? Limitlerimi biliyor muyum? Bunları ne kadar test ettim?
  Bunlara daha pek çok soru eklenebilir. Kendini tanıma bitmeyen bir yolculuktur. Tüm bu sorulara verilen yanıtlar şu en önemli sorunun yanıtını bulmayı kolaylaştırır: Benim potansiyelim nedir? Enerjimi hangi alana yönetmeliyim?
  İşte ve yaşamda başarının anahtarı ilk olarak bu sorunun yanıtında gizlidir. Potansiyelin yüksek olduğu alanlar, en başından iyi ve doğru tanımlanırsa, gelişim yolculuğu bu alana doğru yönlendirebilir. Kariyer süreci de olabildiğince buna göre inşa edildiğinde, kariyer boyunca karşılaşılabilecek sayısız durum, zorluk, meydan okuma ile daha iyi baş etmek mümkün olur. 
  İyi bir işin tarifi de tam burada gizlidir: Sevdiğim, istediğim ve güçlü olduğum bir alanda zorlukların üstesinden gelerek değer üretebildiğim ve bunun karşılığını alabildiğim bir iş... 
  O halde kendini tanımak, iyi bir iş ve iyi bir yaşam için en öncelikli ve sürekli olarak devam eden bir keşif sürecidir.`,
  [
    "Bu yetkinliği geliştirmenin en iyi yolu sürekli olarak sorular sorarak kendi içinizde yolculuğa çıkmaktır.",
    "Her yolculuk öncesi olduğu gibi kendine yolculuk öncesinde de gidilmesi gereken yerler, bakılması gereken noktalar, açılması gereken kapılar, alınması gereken anahtarlar vb. sorularla iyi bir hazırlık yapmak şarttır.",
    "Bu gelişim için öncelikle Tobeto tarafından sunulan ve size belirli bir yolculuk donanımı kazandırmada yardımcı olacak eğitimleri tamamlamanızı öneririz.",
    "Bu eğitimlerin dışında da başka kaynakları araştırın. “Kendimi nasıl daha iyi tanıyabilirim”, “Kendimi tanımak için sorular”, “duysal zekâ” gibi anahtar kelimelerle arama yapın ve kendi soru setinizi oluşturun. Testler, düşünme teknikleri, analiz yöntemleri, soru setleri gibi size yardımcı olabilecek araçları araştırın ve bunları yeri geldiğinde kullanın.",
    "Kendini tanımanın amacı ve odağı gelecektir. İyi bir gelecek inşa etmek için yatırım alanlarını belirlemektir. Bunun için geçmişe ve negatif alanlara takılmadan, pozitif, çözüm odaklı ve yapıcı bir düşünce yapısı geliştirmek çok yardımcı olur.",
    "Bu yetkinlik alanında dış göz son derece kritiktir. Bazen insanın kendine kör olduğu alanlar dışarıdan daha iyi gözlemlenebilir. O yüzden olabilecek her fırsatta geribildirim alın.",
    "Gözlem yapın ve başkalarının deneyimlerinden yararlanın. Özellikle alanında başarılı insanların kendini tanıma sürecindeki deneyimlerini öğrenmeye çalışın.",
    "Fiziksel kapasite ve sağlık, kendini tanıma sürecinde en önemli alanlarından birisidir. Vücudunuzu iyi tanıyın, limitlerinizi iyi öğrenin ve sağlığınızı en üst düzeyde tutmak için elinizden gelen her şeyi yapın.",
    "Yine tekrar edelim. Düzenli olarak kendi içinizde yolculuklara çıkarak, kendi değişiminizi gözlemleyebilir, sizi şaşırtacak ve geleceğinizi şekillendirecek sürpriz keşifler yapma ihtimalinizi artırabilirsiniz."
  ],
  " ",
  `Hem sosyal hem de iş yaşamında başarıyı getiren değerli unsurlardan birisi de amaca yönelik iş birlikleridir. Farklı özelliklerde bir grup insanın bir araya gelmesiyle ortaya çıkan şey, bu insanların toplamından farklı bir şeye dönüşür. Sinerji denilen olgu da tam olarak bunu ifade eder. O halde bir iş yaparken akıl ve emek birliği yapıp bir ekip olabilmek, daha önce olmayan yeni bir güç yaratmaktır. Ekipler, kendini oluşturan bireylerden bağımsız, kendileri de bir çeşit karmaşık varlıktır ve hiç beklenmedik sonuçlar üretme potansiyeli bulunmaktadır. 
  Bu sebeple, birlikte çalışabilmek en önemli güç yetkinliklerinden birisidir. Ekipler içinde herkes kendi bilgisi ve deneyimini ortaya koyar. Herkes ekibe farklı seviyelerde destek verir. Birisi, ekip içinde sadece kendisine düşen işleri yerine getirirken, başka birisi ekibe yön veren lider olabilir. Bir başkası anlaşmazlık durumlarında devreye giren arabulucu olurken, birisi özellikle ekibi motive edip enerjisini yükseltebilir. Zorluk anında birisinin bulduğu yaratıcı bir çözüm tüm ekibi rahatlatırken, başka birisinin deneyimi ve bilgeliği, ekibin hata yapmasının önüne geçebilir. Herkes bir ekipte birden fazla rol üstlenebilir, farklı ekiplerde farklı rollerde görev alabilir.
  Ekipler şirketlerin ve tüm kurumların dinamosudur. Kendi misyonuna göre odaklı ve hedefli bir şekilde çalışan organizmalardır. Çalışan sayısı ne kadar artarsa artsın, bir kurumun en tepeden en aşağıya kadar yönetilmesini mümkün kılan iş birimleridir. Ekipler öğrenmenin, gelişimin, sosyalleşmenin, deneyim paylaşımının, yaratıcılığın, yeniliğin ve büyümenin de çekirdekleridir. Takım oyuncusu olmak, iş yaşamında başarılı olmak isteyen herkesin özellikle geliştirmesi gereken yetkinliklerden birisidir. `,
  ["Ne kadar takım oyuncusu olduğunuz üzerinde kafa yorun. Kendinize bir takım oyuncusu puanı verin. Tobeto ‘İşte Başarı Modeli’ dışında da takım oyuncusu olmakla ilgili testler bulup kendinizi bu konuda daha iyi tanıyabilirsiniz.",
    "Olabildiğince takım çalışmaları içinde yer alın ve deneyiminizi artırın. Bunları yaparken aynı zamanda bilinçli gözlemci olun ve başarıya götüren veya sorun yaratan unsurları kayıt altına alın.",
    "Tobeto’nun takım çalışması ile ilgili sunduğu eğitimleri özellikle tamamlayın. Bu eğitimlerden öğrendiklerinizden yola çıkarken kendi takım oyuncusu manifestonuzu yazın.",
    "İş içinde ya da dışında belirli bir amaca dönük olarak gönüllü takımlar kurabilir, takım kurma ve yönetme deneyiminizi artırabilirsiniz.",
    "Okulda, iş ortamında ya da farklı yerlerde yaptığınız ekip çalışmalarında sizi en çok zorlayan konuları listelemeye çalışın. Hem deneyimlerinizden hem öğrendiklerinizden, bunların çözüm yolları ile ilgili stratejiler oluşturun.",
    "Takımlarda üstlenilebilecek olası rolleri ve takımın başarısına katkı sağlama yollarını araştırın. Daha çok mucit misiniz, şekillendirici mi, yoksa değerlendirici mi, uygulayıcılık size daha mı uygun, yoksa iş bitirici misiniz... kendinizi analiz edin.",
    "Yetkinlikle ilgili bilgi altyapınızı güçlendirmek için “takım rolleri”, “takımların bilgeliği”, “ekip ya da takım çalışması”, “takım olmak”, “ekip ruhu” gibi anahtar kelimelerle araştırma yapabilirsiniz.",
    "Ekip üyelerinin motivasyonu bir ekibi ayakta tutan ve ileriye götüren en önemli güçtür. Kendi deneyimlerinizden ya da edindiğiniz bilgilerden yola çıkarak ekip içinde motivasyonu artıran ve düşüren unsurların bir listesini yapın, paylaşın ve bunu ekip arkadaşlarınızla birlikte geliştirin.",
    "İyi çalışan takımları gözlemleyin. Neyi nasıl yaptıklarını öğrenmeye çalışın. Takım olarak başka takımlarla deneyim paylaşımları da yapabilirsiniz.",
    "Uzmanlığı sadece takımlar olan, takım rehberi, takım koçu olarak hizmet veren kişilerle karşılaşırsanız bunlardan tavsiyeler almaya çalışın."
  ],
  " ",
  `Sürekli gelişim yetkinliği, kendini tanımak gibi yaşamsal önemde bir yetkinliktir. Sadece belirli bir davranış setinden ibaret olmayan daha bütünsel bir zihin yapısıdır. Hiç bitmeyen bir inşa sürecidir. Şu an yapamadığım ama potansiyel olarak yapabileceğim tüm şeyler için gerekli altyapıyı oluşturma sürecidir. Bu açıdan gelişim, gerçekleşmesi mümkün ama henüz gerçekleşmemiş olan her şey için yapılan yolculuktur. Kendimizi doğru bir şekilde tanıdıktan ve buna göre hedeflerimizi net olarak belirledikten sonra bizi hedefe ulaştıracak olan kilit çabadır. 
Sürekli gelişim yetkinliği insana çeviklik kazandırır. Çeviklik, 21. yüz yılın karmaşık ve değişken ortamında en kritik yetkinliklerinden birisi haline gelmiştir. Yeterince çeviksem, değişen koşullara hızla uyum sağlayabilir, daha başarılı ve mutlu olacağım bir kariyer fırsatına hızla geçiş yapabilir veya işimi daha iyi yapmamı sağlayacak bir teknolojiyi hemen öğrenip uygulayabilirim. Ben kendimi sürekli olarak geliştiren çevik birisiyim. Her şeyi öğrenebilir, her şeyi yapabilirim. İşte bu güvenli duruşu sağlayan şey gelişim odaklı zihin yapısıdır ve bu, başarı için gerekli olan bakış açısıdır.
Çeviklik ve sürekli gelişim iş hayatında da olmazsa olmaz bir yetkinliktir. Bir iş demek aynı zamanda bir performans beklentisi demektir. Yani görev aldığınız pozisyona göre sizden beklenen bir başarı vardır. Bunun için yeterli kapasiteniz yoksa en başından bunu geliştirmeniz gerekir. Sonrasında ise işin doğası, kapsamı, derinliği değişebilir, yeni görevler üstlenebilirsiniz, geçici olarak başka görevlerde çalışabilirsiniz; yani performans beklentisi sürekli olarak değişebilir. Buna uyum sağlamanızı mümkün kılacak olan da sürekli gelişim gücünüzdür. 
Kısaca sürekli gelişim, bir iş bulmak, o işte kalıcı ve başarılı olmak, hatta başka işlere yelken açmak için kilit yetkinliğinizdir.`,
  ["Bu yetkinliği geliştirmenin en iyi yolu sürekli olarak gelişim denemeleri yapmak ve bu denemeleri gözlemleyerek iyileştirmektir.",
    "Düşünmek, öğrenmek, gelişmek kuşkusuz en kritik temel yetkinliklerdir. Bunların etkinliğini artırmak için bir üst düzeye çıkıp bunları gözlemlemek ve iyileştirmek mümkündür. Yani düşünme üzerine düşünmek, öğrenmeyi öğrenmek, gelişim yetkinliğini daha da geliştirmek için elinizden gelen tüm çabayı gösterin.",
    "Bunun için Tobeto tarafından size sunulan eğitimleri mutlaka tamamlayın.",
    "Bunun dışında “gelişim odaklı zihin yapısı”, “growth mindset”, “öğrenmeyi öğrenmek”, “sürekli öğrenme”, “sürekli gelişim” ve “çevik olmak” anahtar kelimelerinde araştırma yapın. Bu araştırmalar sonunda harika bilgilere ulaşacaksınız. Önemli gördüğünüz bilgileri özetleyin ve kendinize sürekli hatırlatın.",
    "Kendinize bir gelişim planı hazırlayın ve sürekli olarak güncelleyin. Bu planda “hangi alanda gelişmem gerekli, bu alanda neden ve ne kadar gelişmeliyim, bu süreci ne kadar zamanda tamamlamalıyım, nasıl gelişeceğim ve geliştiğimi nasıl anlayacağım?” sorularının yanıtı mutlaka olsun. Gelişim süreci boyunca da aldığınız mesafeyi ve buradaki kazanımlarınızı not alın.",
    "Yeni olduğunuz alanlarda iyi ve yapılandırılmış bilgilere ulaşmak işinizi kolaylaştırır. Tobeto gibi güvenilir kaynaklara başvurun. Biraz daha deneyimli olduğunuz alanlarda bireysel keşifleriniz ve başkalarının desteğine daha sık başvurabilirsiniz.",
    "Gelişim iş birlikleri kurun. Başkalarının bilgisi ve deneyimi en kıymetli gelişim hazinesidir. Gelişim süreci yürüttüğünüz alanlarda destek alabileceğiniz kişileri belirleyin ve dinamik bir gelişim ağı inşa edin.",
    "Bildiklerinizi başkalarına öğretin, deneyimlerinizi paylaşın, yazın, eğitimler hazırlayın. Öğretmek, öğrenmenin en iyi yollarından birisidir. Başkalarına vereceğiniz gelişim desteği kendi gelişiminiz için farkındalığınızı artırır.",
    "Bilgilenin, deneyin, alıştırma yapın, uygulayın. Gelişimin anahtarı budur. Temel bilgileri edindikten sonra bir an önce deneme ve uygulamaya geçmek önemlidir. Denemelerden gelen deneyim son derece geliştirici ve ufuk açıcıdır. Buluşların, yeniliklerin ve değer yaratan gelişimin anahtarı bu döngüdür."
  ],
  " ",
];

export default descriptions;
